# Generated by Django 2.2.12 on 2020-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
