# Generated by Django 2.2.12 on 2020-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_github_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
