# Generated by Django 2.2.12 on 2020-04-23 19:28

from django.db import migrations

import djongo.models.fields
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="organization",),
        migrations.RemoveField(model_name="project", name="repository",),
        migrations.AddField(
            model_name="project",
            name="columns",
            field=djongo.models.fields.ArrayField(
                default=[], model_container=project.models.ProjectColumn
            ),
            preserve_default=False,
        ),
    ]
