# Generated by Django 2.2.12 on 2020-04-27 17:19

import django.db.models.deletion
from django.db import migrations

import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_auto_20200423_1928"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repositories",
            field=djongo.models.fields.ArrayReferenceField(
                default=[],
                on_delete=django.db.models.deletion.CASCADE,
                to="project.Repository",
            ),
            preserve_default=False,
        ),
    ]
