# Generated by Django 2.2.12 on 2020-04-23 20:36

import django.db.models.deletion
from django.db import migrations, models

import djongo.models.fields
import issue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0004_auto_20200423_1928"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=100)),
                ("labels", models.CharField(max_length=255, blank=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("feature", "Feature"),
                            ("bug", "Bug fix"),
                            ("chore", "Chore/Maintenance"),
                            ("qa", "QA Automation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("expedite", "Expedite"),
                            ("fixed", "Fixed Delivery Date"),
                            ("standard", "Standard"),
                            ("intangible", "Intangible"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "timeline",
                    djongo.models.fields.ArrayField(
                        blank=True, model_container=issue.models.Event
                    ),
                ),
                ("done", models.BooleanField(blank=True, default=False)),
                ("created_at", models.DateTimeField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True)),
                ("kanban_start_date", models.DateTimeField(blank=True)),
                ("kanban_end_date", models.DateTimeField(blank=True)),
                ("kanban_lead_time", models.PositiveIntegerField(blank=True)),
                ("kanban_metrics", djongo.models.fields.DictField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.Project",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.Repository",
                    ),
                ),
            ],
            options={"unique_together": {("repo", "number", "project")},},
        ),
    ]
