# Generated by Django 2.2.12 on 2020-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="invalid",
            field=models.BooleanField(default=False),
        ),
    ]
